version: '3'

services:
  ##########################################
  # Overrides for oada-core services:
  ##########################################

  # Add ourselves to yarn to do yarn install
  yarn:
    volumes:
      - ./services-available/trellis-signer:/code/trellis-signer

  # Add ourselves to admin container:
  admin:
    volumes:
      - ./services-available/trellis-signer:/code/trellis-signer

  ###############################################
  # This service's definition:
  ###############################################
  trellis-signer:
    depends_on:
      - startup
    build:
      context: ./services-available/trellis-signer
    container_name: trellis-signer
    restart: always
    networks:
      - http_net
      - startup_net
      - arango_net
    volumes:
      - ./services-available/trellis-signer:/code/trellis-signer
      - ./oada-core/libs:/code/libs
      - ./oada-srvc-docker-config.js:/oada-srvc-docker-config.js
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-"trellis-signer:info,*warn*,*error*"}
      - domain
      - token
