version: '3'

services:
  trellis-signer:
    build: .
    container_name: trellis-signer
    restart: always
    volumes:
      - ./trellis-signer:/code/trellis-signer
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG=${DEBUG:-"trellis-signer:info,*warn*,*error*"}
      - domain
      - token
